- project:
    templates:
      - build-openstack-docs-pti
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python3-victoria-jobs
    check:
      jobs:
        - legacy-tempest-dsvm-monasca-transform-python35-functional:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
