- project:
    templates:
      - build-openstack-docs-pti
      - check-requirements
      - openstack-cover-jobs
      - openstack-lower-constraints-jobs
      - openstack-python-jobs
      - openstack-python35-jobs
      - openstack-python36-jobs
      - openstack-python37-jobs
    check:
      jobs:
        - legacy-tempest-dsvm-monasca-transform-python-functional:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
        - legacy-tempest-dsvm-monasca-transform-python35-functional:
            voting: false
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$
    gate:
      jobs:
        - legacy-tempest-dsvm-monasca-transform-python-functional:
            irrelevant-files:
              - ^(test-|)requirements.txt$
              - ^setup.cfg$

